/*In this exercise, we’ve started to declare some variables but we don’t know the answers to the questions. You should fill in the rest of the lines to make them correct.

String bestFriendsName  ...
int luckyNumber ...
double ...
boolean ...
Edit the code so that the output of running the program is:

Tracy the Turtle
3
115.46
false */

public class Variables 
{
    public static void main(String[] args)
    {
        String bestFriendsName = "Tracy the Turtle";
        int luckyNumber = 3;
        double roomSqFootage = 115.46;
        boolean doesBallet =  false;
        
        System.out.println(bestFriendsName);
        System.out.println(luckyNumber);
        System.out.println(roomSqFootage);
        System.out.println(doesBallet);
    }
}